import { registerEnumType } from '@nestjs/graphql';

export enum HabitIconEnum {
    purple1 = "purple1",
    purple2 = "purple2",
    purple3 = "purple3",
    purple4 = "purple4",
    orange1 = "orange1",
    orange2 = "orange2",
    orange3 = "orange3",
    orange4 = "orange4",
    cyan1 = "cyan1",
    cyan2 = "cyan2",
    cyan3 = "cyan3",
    cyan4 = "cyan4",
    red1 = "red1",
    red2 = "red2",
    red3 = "red3",
    red4 = "red4",
    red5 = "red5",
    red6 = "red6",
    red7 = "red7",
    blue1 = "blue1",
    blue2 = "blue2",
    blue3 = "blue3",
    blue4 = "blue4",
    green1 = "green1",
    green2 = "green2",
    green3 = "green3",
    green4 = "green4",
    pink1 = "pink1",
    pink2 = "pink2",
    pink3 = "pink3",
    pink4 = "pink4",
    pink5 = "pink5",
    pink6 = "pink6",
    pink7 = "pink7",
    yellow1 = "yellow1",
    yellow2 = "yellow2",
    yellow3 = "yellow3",
    yellow4 = "yellow4",
    brown1 = "brown1",
    brown2 = "brown2",
    brown3 = "brown3",
    brown4 = "brown4",
    brown5 = "brown5",
    brown6 = "brown6",
    brown7 = "brown7",
    purple5 = "purple5",
    purple6 = "purple6",
    purple7 = "purple7",
    purple8 = "purple8",
    orange5 = "orange5",
    orange6 = "orange6",
    orange7 = "orange7",
    orange8 = "orange8",
    cyan5 = "cyan5",
    cyan6 = "cyan6",
    cyan7 = "cyan7",
    cyan8 = "cyan8",
    red8 = "red8",
    red9 = "red9",
    red10 = "red10",
    red11 = "red11",
    red12 = "red12",
    blue5 = "blue5",
    blue6 = "blue6",
    blue7 = "blue7",
    green5 = "green5",
    green6 = "green6",
    green7 = "green7",
    green8 = "green8",
    pink8 = "pink8",
    brown8 = "brown8"
}


registerEnumType(HabitIconEnum, { name: 'HabitIconEnum', description: undefined })
